version: '3.1'

services:
  mysql-server-1:
    image: ${MYSQLSERVER_IMAGE}
    command:
      - "mysqld"
      - "--server_id=1"
      - "--binlog_checksum=NONE"
      - "--gtid_mode=ON"
      - "--enforce_gtid_consistency=ON"
      - "--log_bin"
      - "--log_slave_updates=ON"
      - "--master_info_repository=TABLE"
      - "--relay_log_info_repository=TABLE"
      - "--transaction_write_set_extraction=XXHASH64"
      - "--user=mysql"
      - "--skip-host-cache"
      - "--skip-name-resolve"
      - "--default_authentication_plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
  mysql-server-2:
    image: ${MYSQLSERVER_IMAGE}
    command:
      - "mysqld"
      - "--server_id=2"
      - "--binlog_checksum=NONE"
      - "--gtid_mode=ON"
      - "--enforce_gtid_consistency=ON"
      - "--log_bin"
      - "--log_slave_updates=ON"
      - "--master_info_repository=TABLE"
      - "--relay_log_info_repository=TABLE"
      - "--transaction_write_set_extraction=XXHASH64"
      - "--user=mysql"
      - "--skip-host-cache"
      - "--skip-name-resolve"
      - "--default_authentication_plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
  mysql-server-3:
    image: ${MYSQLSERVER_IMAGE}
    command:
      - "mysqld"
      - "--server_id=3"
      - "--binlog_checksum=NONE"
      - "--gtid_mode=ON"
      - "--enforce_gtid_consistency=ON"
      - "--log_bin"
      - "--log_slave_updates=ON"
      - "--master_info_repository=TABLE"
      - "--relay_log_info_repository=TABLE"
      - "--transaction_write_set_extraction=XXHASH64"
      - "--user=mysql"
      - "--skip-host-cache"
      - "--skip-name-resolve"
      - "--default_authentication_plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
  mysql-shell:
    image: neumayer/mysql-shell-batch
    volumes:
      - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
    environment:
      MYSQL_USER: root
      MYSQL_HOST: mysql-server-1
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQLSH_SCRIPT: /scripts/setupCluster.js
      MYSQL_SCRIPT: /scripts/db.sql
  cache:
    image: ${REDIS_IMAGE}
  theo1:
    image: theo:test
    container_name: theo1
    restart: always
    environment:
      MODE: test
      LOG_LEVEL: debug
      DB_ENGINE: mariadb
      DB_CLUSTER: rw:mysql-server-1:3306,ro:mysql-server-2:3306,ro:mysql-server-2:3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      CORE_TOKEN: ${CORE_TOKEN}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      CLUSTER_MODE: 1
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - cache
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
  theo2:
    image: theo:test
    container_name: theo2
    restart: always
    environment:
      MODE: test
      LOG_LEVEL: debug
      DB_ENGINE: mariadb
      DB_CLUSTER: rw:mysql-server-1:3306,ro:mysql-server-2:3306,ro:mysql-server-2:3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      CORE_TOKEN: ${CORE_TOKEN}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      CLUSTER_MODE: 1
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - cache
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
  theo3:
    image: theo:test
    container_name: theo3
    restart: always
    environment:
      MODE: test
      LOG_LEVEL: debug
      DB_ENGINE: mariadb
      DB_CLUSTER: rw:mysql-server-1:3306,ro:mysql-server-2:3306,ro:mysql-server-2:3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      CORE_TOKEN: ${CORE_TOKEN}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      CLUSTER_MODE: 1
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - cache
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3

