version: '3.1'

services:
  db:
    image: ${MYSQLSERVER_IMAGE}
    container_name: mysql-server
    command: ["mysqld","--skip-host-cache","--skip-name-resolve"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  theo:
    image: theo:test
    container_name: theo
    environment:
      MODE: test
      DB_ENGINE: mysql
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      CLIENT_TOKENS: ${CLIENT_TOKENS}
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - db
