version: '3.1'

services:
  db:
    image: ${MARIADB_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  cache:
    image: ${REDIS_IMAGE}
  theo1:
    image: theo:test
    container_name: theo1
    environment:
      MODE: test
      DB_ENGINE: mariadb
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      CORE_TOKEN: ${CORE_TOKEN}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      CLUSTER_MODE: 1
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - cache
      - db
  theo2:
    image: theo:test
    container_name: theo2
    environment:
      MODE: test
      DB_ENGINE: mariadb
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      CORE_TOKEN: ${CORE_TOKEN}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      CLUSTER_MODE: 1
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - cache
      - db
  theo3:
    image: theo:test
    container_name: theo3
    environment:
      MODE: test
      DB_ENGINE: mariadb
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      CORE_TOKEN: ${CORE_TOKEN}
      CACHE_ENABLED: redis
      CACHE_URI: redis://cache:6379
      CLUSTER_MODE: 1
      DB_CONN_MAX_RETRY: 30
      SKIP_UPDATECHECK: 1
    depends_on:
      - cache
      - db
