version: '3.1'

services:
  cache:
    image: ${MEMCACHED_IMAGE}
  theo:
    image: theo:test
    container_name: theo
    environment:
      - MODE=test
      - DB_STORAGE=":memory:"
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - CLIENT_TOKENS=${CLIENT_TOKENS}
      - CACHE_ENABLED=memcached
      - CACHE_URI=cache:11211
      - SKIP_UPDATECHECK=1
    depends_on:
      - cache
