name: Node.js CI test

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm i -g npm
    - run: npm ci
    - run: npm run lint

  test:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g npm
      - run: npm ci --no-optional
      - run: npm run test:standalone

  build:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g npm
      - run: npm ci --no-optional
      - run: npm run build --if-present
