# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-test-build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run lint
    - run: npm run test:standalone
    - run: npm run build --if-present

  full-test:
    runs-on: ubuntu-latest
    needs: lint-test-build
    steps:
    - uses: actions/checkout@v2
    - run: ./runTestsAll.sh