# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI e2e

on:
  pull_request:
    branches: [ master ]

jobs:
  full-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./runTestsAll.sh