name: Node.js CI e2e

on:
  pull_request:
    branches: [ master ]

jobs:
  full-test:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      if: env.DOCKER_PASSWORD != null
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: ./runTestsAll.sh